// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4uj4z-vom-9431zJeZ7nt0XvxreFR6Cg',
    appId: '1:95507811854:web:e39ebdc9ed8f916dfc765f',
    messagingSenderId: '95507811854',
    projectId: 'kart-project-cdfed',
    authDomain: 'kart-project-cdfed.firebaseapp.com',
    storageBucket: 'kart-project-cdfed.appspot.com',
    measurementId: 'G-B93L3MS3BR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP9MpY4i2VK0gQsuliyNMfzuH66MN0uwI',
    appId: '1:95507811854:android:a5053ab172102a66fc765f',
    messagingSenderId: '95507811854',
    projectId: 'kart-project-cdfed',
    storageBucket: 'kart-project-cdfed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1sF7TDs-VIFhFeh-M9TtMHodVk89k49g',
    appId: '1:95507811854:ios:dcdab606083a4fd7fc765f',
    messagingSenderId: '95507811854',
    projectId: 'kart-project-cdfed',
    storageBucket: 'kart-project-cdfed.appspot.com',
    iosBundleId: 'com.example.machineTestTotalx',
  );

}