// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDONPlQyMXrQBpLmi-3ZG7C8Ge5hYSGZn0',
    appId: '1:832545867949:web:bd6d435aae842d7a705e24',
    messagingSenderId: '832545867949',
    projectId: 'machine-test-totalx',
    authDomain: 'machine-test-totalx.firebaseapp.com',
    storageBucket: 'machine-test-totalx.firebasestorage.app',
    measurementId: 'G-JS5358YQNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZmRW75SZqUNlm5y8eLQmXxyzL8CNRZCw',
    appId: '1:832545867949:android:adbd47d25df34701705e24',
    messagingSenderId: '832545867949',
    projectId: 'machine-test-totalx',
    storageBucket: 'machine-test-totalx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9cxJz-pNEAB_ulpYx0GZZJ8eeL3xVfIU',
    appId: '1:832545867949:ios:f1063563674578fe705e24',
    messagingSenderId: '832545867949',
    projectId: 'machine-test-totalx',
    storageBucket: 'machine-test-totalx.firebasestorage.app',
    iosBundleId: 'com.example.machineTestTotalx',
  );
}
